project:
  type: website

website:
  title: "Abhimanyu Yadav"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EkShunyam
      - icon: twitter
        href: https://twitter.com/ekshunyam
format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    mainfont: Roboto
    css: styles.css
    toc: true



