project:
  type: website

website:
  title: "Abhimanyu Yadav"
  site-url: https://ekshunyam.github.io/
  google-analytics: "G-PJE6CQ07D5"
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EkShunyam
      - icon: twitter
        href: https://twitter.com/ekshunyam
format:
  html:
    theme: 
      light: sandstone
      dark: cyborg
    mainfont: Roboto
    css: styles.css
    toc: true



